# gandalfmagic/nodejs-chrome:19.4.0-bullseye-1
# reference: https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeChrome/Dockerfile
FROM debian:11.6-slim AS build

ARG SONAR_VERSION="4.8.0.2856"

RUN apt update && apt install -y wget unzip && rm -rf /var/lib/apt/lists/* /var/cache/apt/* && \
    wget --quiet -O /tmp/sonar-scanner-cli-linux.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux.zip && \
    cd /tmp/ && unzip sonar-scanner-cli-linux.zip && \
    mv /tmp/sonar-scanner-${SONAR_VERSION}-linux /tmp/sonar-scanner && \
    sed -i 's/^use_embedded_jre=true.*/use_embedded_jre=false/' /tmp/sonar-scanner/bin/sonar-scanner

FROM node:19.4.0-bullseye-slim

ARG CHROME_VERSION="google-chrome-stable"
ARG NPM_VERSION="9.2.0"
ENV CHROME_BIN="/usr/bin/${CHROME_VERSION}"
ENV PATH="${PATH}:/opt/sonar-scanner/bin"

# Install latest Google Chrome
RUN apt update && apt install -y curl wget gnupg2 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    npm install -g npm@${NPM_VERSION} && \
    # revolve BUG: https://github.com/debuerreotype/docker-debian-artifacts/issues/24
    mkdir -p /usr/share/man/man1 && \
    apt update && apt install -y --no-install-recommends git ${CHROME_VERSION:-google-chrome-stable} default-jre-headless && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*

COPY --from=build /tmp/sonar-scanner/lib /opt/sonar-scanner/lib
COPY --from=build /tmp/sonar-scanner/conf /opt/sonar-scanner/conf
COPY --from=build /tmp/sonar-scanner/bin /opt/sonar-scanner/bin

# Add Chrome as a user
RUN mkdir -p /usr/src/app \
    && useradd --user-group --create-home chrome \
    && chown -R chrome:chrome /usr/src/app
# Run Chrome as non-privileged user
USER chrome
WORKDIR /usr/src/app
